modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ne_mod"
version="1.0.0"
displayName="NE_Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="21ethabeau, MCreator"

[[dependencies.ne_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




